// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu9kR0XQ83gjuJLOFXVGz58VMNCM0sQ08',
    appId: '1:860721395575:web:240c6785045acd14e5d372',
    messagingSenderId: '860721395575',
    projectId: 'ai-powered-fra',
    authDomain: 'ai-powered-fra.firebaseapp.com',
    storageBucket: 'ai-powered-fra.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Hpy4qWU43OLjH67iTz6oT42sbccs_kk',
    appId: '1:860721395575:android:ae462b6ef9ab3ae8e5d372',
    messagingSenderId: '860721395575',
    projectId: 'ai-powered-fra',
    storageBucket: 'ai-powered-fra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB01XuZ0XNaG5wza7YGXXmuY6KjK931DcM',
    appId: '1:860721395575:ios:57d8462d3e4e7d9ce5d372',
    messagingSenderId: '860721395575',
    projectId: 'ai-powered-fra',
    storageBucket: 'ai-powered-fra.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB01XuZ0XNaG5wza7YGXXmuY6KjK931DcM',
    appId: '1:860721395575:ios:57d8462d3e4e7d9ce5d372',
    messagingSenderId: '860721395575',
    projectId: 'ai-powered-fra',
    storageBucket: 'ai-powered-fra.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu9kR0XQ83gjuJLOFXVGz58VMNCM0sQ08',
    appId: '1:860721395575:web:3a5c7c746a6fc3e0e5d372',
    messagingSenderId: '860721395575',
    projectId: 'ai-powered-fra',
    authDomain: 'ai-powered-fra.firebaseapp.com',
    storageBucket: 'ai-powered-fra.firebasestorage.app',
  );
}
